# base-image for python on any machine using a template variable,
# see more about dockerfile templates here: https://www.balena.io/docs/learn/develop/dockerfile/
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-build

WORKDIR /home/root

COPY . ./subscriber

RUN pip install --upgrade pip
RUN pip install -r subscriber/requirements.txt

CMD ["python", "-um", "subscriber.app"]
