version: "2"

volumes:
  dbdata:

services:
  db:
    build:
      context: ./db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    depends_on:
      - db
    build:
      context: ./server
    ports:
      - 80:80

  subscriber:
    depends_on:
      - db
    build:
      context: ./subscriber
