version: "2"

services:
  server:
    build:
      context: ./server
    ports:
      - 80:80
  db:
    build:
      context: ./db
    environment:
      POSTGRES_PASSWORD: lorem
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
