version: "2"

volumes:
  dbdata:

services:
  db:
    build:
      context: ./db
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    depends_on:
      - db
    build:
      context: ./server
    ports:
      - 80:80
