# base-image for python on any machine using a template variable,
# see more about dockerfile templates here: https://www.balena.io/docs/learn/develop/dockerfile/
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-build

EXPOSE 80

WORKDIR /home/root

COPY . ./server

RUN pip install --upgrade pip
RUN pip install -r server/requirements.txt

CMD ["python", "-um", "server.app"]
