# base-image for python on any machine using a template variable,
# see more about dockerfile templates here: https://www.balena.io/docs/learn/develop/dockerfile/
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run

EXPOSE 80

WORKDIR /home/root/

COPY . ./

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# main.py will run when container starts up on the device
CMD ["python", "-u", "src/main.py"]
